# dbt_project/dbt_project.yml

name: 'pd_transforms'        
version: '1.0.0'
config-version: 2

profile: 'pd_portfolio'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]


seeds:
  pd_transforms:
    +delimiter: ","
    +quote: ""
    +header: true
    +column_types: {}   
    +csv_reader_options:
      all_varchar: true  

models:
  pd_transforms:               
    +materialized: table       